[package]
name = "rdbms"
version = "0.1.0"
authors = ["Yorinton <ka2ki.yori@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pagecache = "0.19.4"
rand = "0.8.3"
